name: devops-plateform-frontend

on:
  push:
    branches: [ main ]
    paths:
      - "apps/web/**"

env:
  NAME: tlowac
  REPO: devops-platform-frontend
  REGISTRY_PREFIX: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build with pnpm
        run: pnpm build

      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{env.NAME}}
          password: ${{secrets.DOCKER_REGISTRY_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/web/Dockerfile
          push: true
          tags: ${{env.REGISTRY_PREFIX}}/${{env.NAME}}/${{env.REPO}}:latest